## XGBoost

### Import libraries and data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
dataset = pd.read_csv('Data.csv')
dataset = dataset.drop('Sample code number', axis = 1)

In [2]:
dataset.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2

### Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset.apply(le.fit_transform)

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,4,0,0,0,1,0,2,0,0,0
1,4,3,3,4,6,9,2,1,0,0
2,2,0,0,0,1,1,2,0,0,0
3,5,7,7,0,2,3,2,6,0,0
4,3,0,0,2,1,0,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...
678,2,0,0,0,2,1,0,0,0,0
679,1,0,0,0,1,0,0,0,0,0
680,4,9,9,2,6,2,7,9,1,1
681,3,7,5,3,2,3,9,5,0,1
682,3,7,7,4,3,4,9,3,0,1

### Train Test Split

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### XGBoost fitting on the Training Set

In [5]:
from xgboost import XGBClassifier
classifier = XGBClassifier(eval_metric='mlogloss',use_label_encoder = False, num_class = 2)
classifier.fit(X_train, y_train)

ValueError: The label must consist of integer labels of form 0, 1, 2, ..., [num_class - 1].

### Making the confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

### Applying k-Fold cross validation

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy : {:.2f} %".format(accuracies.mean() * 100))
print("Standard Deviation : {:.2f} %".format(accuracies.std() * 100))